### ISSUE TITLE
Paths?

### ISSUE THREAD

**Issue by google-feinberg** [martine/gocairo#1]
Do you intend to support all of the Paths functions and types?

http://cairographics.org/manual/cairo-Paths.html

Thanks!

**Comment by evmar** [comment]
I would like to.  The API is a bit tricky (e.g. the path data involves a union) so I was leaving it for later.
http://cairographics.org/manual/cairo-Paths.html#cairo-path-data-t
I'll take a look.

**Comment by evmar** [comment]
See also their discussion of language bindings for paths:
http://cairographics.org/manual/bindings-path.html

**Comment by evmar** [comment]
It looks like we already cover all the functions on the page you linked except for cairo_copy_path, copy_path_flat, append_path, and path_destroy.  Were you looking for those in particular?

**Comment by google-feinberg** [comment]
For what I have in mind, I'd especially need the cairo_glyph_path and cairo_copy_path functions. I need to iterate over all the control points of rendered text.

**Comment by evmar** [comment]
Ah, I haven't touched the glyph bits yet because I also wasn't sure of the API.
I fixed up some code to make it print the reasons it's skipping various bits, see
https://gist.github.com/martine/909657eda5635e12a478

**Comment by evmar** [comment]
The above implemented cairo_glyph_path.

It appears to actually load a font you're stuck with either using the "toy" font API (which includes cairo_select_font_face) or wrapping cairo-freetype (which I haven't looked at yet).

I'll look into cairo_copy_path.

**Comment by evmar** [comment]
I think I have this mostly working, but I have one question about the API.

The underlying API exposes the path as a list of segments, where each segment is one of MoveTo, LineTo, CurveTo, or Close.  The question is how to get at the list.

Option 1 is to do what the Cairo docs suggest, which produces code like this (verbose types so you can see what's happening better):

```
var path *cairo.Path = cr.CopyPath()
var iter *cairo.PathIter = path.Iter()  // starts iteration through the path
for var seg *cairo.PathSegment = iter.Next(); seg != nil; seg = iter.Next() {
  // use segment here
}
```

The other option is to just copy everything into Go up front, e.g. like:

```
var segs []*cairo.PathSegment = path.Segments()
```

This avoids all the iterator machinery at the cost of needing to build up this intermediate array.  (To allocate it, I'd either need to do it in a loop of segs = append(segs, ...) or do an O(n) pass through the path up front to precompute the size of the array.)

What do you think?  How performance critical is this?  My impression is that the Cairo API was designed to trade off memory and performance.

**Comment by google-feinberg** [comment]
Since you're asking, I'd think that you want to directly expose the iterator, since that gives the user the option of building the other, if they happen to need it, but not vice versa.

**Comment by evmar** [comment]
OK, pushed in https://github.com/martine/gocairo/commit/28e38698c9e6d3312fc76736c0b5e1ae27b485d0 .

I think the godoc site might take a day to update, but `examples/path.go` has this:

```
    path := cr.CopyPath()
    iter := path.Iter()
    for seg := iter.Next(); seg != nil; seg = iter.Next() {
        log.Printf("seg %#v", seg)
    }
```

**Comment by google-feinberg** [comment]
Sweet! Thank you!
