### ISSUE TITLE
Support for WriteToSVG

### ISSUE THREAD

**Issue by dgryski** [martine/gocairo#4]
Cairo can draw the current surface as an SVG.  However, this function is not exposed by the gocairo bindings.

**Comment by evmar** [comment]
Fixed in 7df4802ca76711a807613739148b3a540965e2f5 .  Thanks for reporting it!

https://godoc.org/github.com/martine/gocairo/cairo#SVGSurface

**Comment by dgryski** [comment]
Is it possible to wrap https://www.cairographics.org/manual/cairo-SVG-Surfaces.html#cairo-svg-surface-create-for-stream also ?  I started playing with it but I couldn't figure out how to nice cleanup the closure key when I was finished with it.
